# action.yml
name: 'Create and Update Deployment'
description: 'Create a new deployment and update its status'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  ref:
    description: 'Git reference'
    required: true
    default: 'main'
  team-short-name:
    description: 'Use the team short name'
    required: true
  repository:
    description: 'Repository name'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Validate teamname input
      shell: bash
      run: |
        if [[ ! "${{ inputs.team-short-name }}" =~ ^[a-zA-Z]{1,5}$ ]]; then
          echo "Error: 'team-short-name' must be 1-5 letters with no numbers."
          exit 1
        fi
    - name: Create deployment
      id: create_deployment
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        RESPONSE=$(gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.repository }}/deployments \
          -f "ref=${{ inputs.ref }}" -f "environment=kpi-deployment-count" -f "description=team:${{ inputs.team-short-name }}")
        DEPLOYMENT_ID=$(echo $RESPONSE | jq '.id')
        echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
    - name: Update deployment status
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.repository }}/deployments/$DEPLOYMENT_ID/statuses \
          -f "environment=kpi-deployment-count" -f "state=success" -f "description=team:${{ inputs.team-short-name }}"


# # .github/workflows/deployment-workflow.yaml
# name: Deployment Workflow

# on: [push]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup GitHub CLI
#         uses: cli/cli/setup-gh@v1

#       - name: Create and Update Deployment
#         uses: your-username/your-action-repository@main
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           team-short-name: ops